### ISSUE TITLE
Compatibility with Digital RGB header? Support for more colors?

### ISSUE THREAD

**Issue by zybeon** [K4CZP3R/RGB-Fusion-Monoc#1]
Does this support the Digital RGB headers in the newer boards?

Also can this support more than 8 colors? From the read me it looks like it can only support 1 bit per channel, 3-bit color.

**Comment by kacper-serewis** [comment]
I can't test it out, because I don't have a newer board.
Yes, it supports only combinations of 3-bits (R, G, B)
